// ============================================================
// PixelMorpher - Built-in Brush Shape & Style Presets
// ============================================================
// Predefined brush shapes and advanced style presets for pixel art creation.

import type { BrushPreset } from './types';

export const BUILT_IN_BRUSH_PRESETS: BrushPreset[] = [
  // ---- Classic Pixel Brushes (solid style) ----
  {
    id: 'builtin_pixel_1',
    name: '像素点',
    type: 'pixel',
    size: 1,
    shape: [[true]],
  },
  {
    id: 'builtin_square_2',
    name: '2px方块',
    type: 'pixel',
    size: 2,
    shape: [
      [true, true],
      [true, true],
    ],
  },
  {
    id: 'builtin_square_3',
    name: '3px方块',
    type: 'pixel',
    size: 3,
    shape: [
      [true, true, true],
      [true, true, true],
      [true, true, true],
    ],
  },
  {
    id: 'builtin_dash_3',
    name: '短划线',
    type: 'dash',
    size: 3,
    shape: [[true, true, true]],
  },
  {
    id: 'builtin_dash_5',
    name: '长划线',
    type: 'dash',
    size: 5,
    shape: [[true, true, true, true, true]],
  },
  {
    id: 'builtin_cross_3',
    name: '十字',
    type: 'custom',
    size: 3,
    shape: [
      [false, true, false],
      [true, true, true],
      [false, true, false],
    ],
  },
  {
    id: 'builtin_star_5',
    name: '星形',
    type: 'star',
    size: 5,
    shape: [
      [false, false, true, false, false],
      [false, true, true, true, false],
      [true, true, true, true, true],
      [false, true, true, true, false],
      [false, false, true, false, false],
    ],
  },
  {
    id: 'builtin_diamond_3',
    name: '菱形',
    type: 'custom',
    size: 3,
    shape: [
      [false, true, false],
      [true, false, true],
      [false, true, false],
    ],
  },
  {
    id: 'builtin_ring_5',
    name: '环形',
    type: 'custom',
    size: 5,
    shape: [
      [false, false, true, false, false],
      [false, true, false, true, false],
      [true, false, false, false, true],
      [false, true, false, true, false],
      [false, false, true, false, false],
    ],
  },
  {
    id: 'builtin_diagonal_3',
    name: '对角线',
    type: 'custom',
    size: 3,
    shape: [
      [true, false, false],
      [false, true, false],
      [false, false, true],
    ],
  },

  // ---- V5: Advanced Style Brushes ----

  {
    id: 'builtin_glow_orb_warm',
    name: '暖光团',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'glow_orb',
    styleParams: {
      opacity: 0.9,
      hardness: 0.3,
      innerColor: '#ffffff',
      outerColor: '#ff6600',
      innerRadius: 0.25,
      falloff: 0.6,
    },
  },
  {
    id: 'builtin_glow_orb_cool',
    name: '冷光团',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'glow_orb',
    styleParams: {
      opacity: 0.9,
      hardness: 0.3,
      innerColor: '#ffffff',
      outerColor: '#0066ff',
      innerRadius: 0.3,
      falloff: 0.5,
    },
  },
  {
    id: 'builtin_glow_orb_magic',
    name: '魔法光团',
    type: 'pixel',
    size: 7,
    shape: [[true]],
    style: 'glow_orb',
    styleParams: {
      opacity: 0.85,
      hardness: 0.2,
      innerColor: '#ff88ff',
      outerColor: '#4400aa',
      innerRadius: 0.2,
      falloff: 0.7,
    },
  },
  {
    id: 'builtin_dual_flame_fire',
    name: '火焰(白芯红焰)',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'dual_flame',
    styleParams: {
      opacity: 0.9,
      hardness: 0.3,
      innerColor: '#ffffcc',
      outerColor: '#ff2200',
      innerRadius: 0.2,
      falloff: 0.4,
      flickerAmount: 0.4,
      flameDirection: 270,
      elongation: 1.8,
    },
  },
  {
    id: 'builtin_dual_flame_soul',
    name: '灵魂火(蓝芯紫焰)',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'dual_flame',
    styleParams: {
      opacity: 0.85,
      hardness: 0.25,
      innerColor: '#aaddff',
      outerColor: '#6600cc',
      innerRadius: 0.25,
      falloff: 0.5,
      flickerAmount: 0.5,
      flameDirection: 270,
      elongation: 2.0,
    },
  },
  {
    id: 'builtin_dual_flame_ember',
    name: '余烬(黄芯橙焰)',
    type: 'pixel',
    size: 4,
    shape: [[true]],
    style: 'dual_flame',
    styleParams: {
      opacity: 0.8,
      hardness: 0.35,
      innerColor: '#ffee00',
      outerColor: '#ff6600',
      innerRadius: 0.3,
      falloff: 0.3,
      flickerAmount: 0.6,
      flameDirection: 270,
      elongation: 1.5,
    },
  },
  {
    id: 'builtin_spray_fine',
    name: '细喷溅',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'spray',
    styleParams: {
      opacity: 0.8,
      density: 0.3,
      spread: 1.0,
      seed: 1,
    },
  },
  {
    id: 'builtin_spray_coarse',
    name: '粗喷溅',
    type: 'pixel',
    size: 7,
    shape: [[true]],
    style: 'spray',
    styleParams: {
      opacity: 0.9,
      density: 0.6,
      spread: 1.5,
      seed: 2,
    },
  },
  {
    id: 'builtin_neon_glow',
    name: '霓虹光管',
    type: 'pixel',
    size: 2,
    shape: [[true]],
    style: 'neon',
    styleParams: {
      opacity: 1.0,
      hardness: 0.7,
      glowRadius: 3,
      glowIntensity: 0.8,
    },
  },
  {
    id: 'builtin_neon_soft',
    name: '柔光霓虹',
    type: 'pixel',
    size: 1,
    shape: [[true]],
    style: 'neon',
    styleParams: {
      opacity: 0.9,
      hardness: 0.3,
      glowRadius: 5,
      glowIntensity: 0.5,
    },
  },
  {
    id: 'builtin_gradient_radial',
    name: '径向渐变',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'gradient',
    styleParams: {
      opacity: 0.9,
      hardness: 0.4,
      gradientType: 'radial',
      secondaryColor: '#000000',
    },
  },
  {
    id: 'builtin_gradient_linear',
    name: '线性渐变',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'gradient',
    styleParams: {
      opacity: 0.9,
      hardness: 0.4,
      gradientType: 'linear',
      secondaryColor: '#000000',
    },
  },
  {
    id: 'builtin_scatter_stars',
    name: '星尘散布',
    type: 'pixel',
    size: 7,
    shape: [[true]],
    style: 'scatter',
    styleParams: {
      opacity: 0.9,
      density: 0.4,
      spread: 1.5,
      seed: 42,
    },
  },

  // ---- V6: Stroke-Aware Style Brushes ----

  {
    id: 'builtin_tapered_calligraphy',
    name: '书法笔(渐细)',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'tapered',
    styleParams: {
      opacity: 1,
      hardness: 0.8,
      taperLength: 0.2,
      taperCurve: 'smooth',
      minSizeRatio: 0.1,
    },
  },
  {
    id: 'builtin_tapered_whip',
    name: '鞭梢(锐细)',
    type: 'pixel',
    size: 6,
    shape: [[true]],
    style: 'tapered',
    styleParams: {
      opacity: 1,
      hardness: 0.9,
      taperLength: 0.35,
      taperCurve: 'ease_out',
      minSizeRatio: 0.05,
    },
  },
  {
    id: 'builtin_tapered_brush',
    name: '毛笔(圆头渐细)',
    type: 'pixel',
    size: 4,
    shape: [[true]],
    style: 'tapered',
    styleParams: {
      opacity: 0.95,
      hardness: 0.6,
      taperLength: 0.15,
      taperCurve: 'smooth',
      minSizeRatio: 0.2,
    },
  },
  {
    id: 'builtin_pipe_metal',
    name: '金属管道',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'pipe',
    styleParams: {
      opacity: 1,
      hardness: 0.8,
      highlightPosition: 'top',
      highlightSize: 0.25,
      highlightIntensity: 0.7,
      wallShade: 0.5,
    },
  },
  {
    id: 'builtin_pipe_hose',
    name: '软管(低对比)',
    type: 'pixel',
    size: 6,
    shape: [[true]],
    style: 'pipe',
    styleParams: {
      opacity: 1,
      hardness: 0.5,
      highlightPosition: 'top',
      highlightSize: 0.4,
      highlightIntensity: 0.3,
      wallShade: 0.25,
    },
  },
  {
    id: 'builtin_pipe_crystal',
    name: '水晶管道(强高光)',
    type: 'pixel',
    size: 4,
    shape: [[true]],
    style: 'pipe',
    styleParams: {
      opacity: 0.95,
      hardness: 0.9,
      highlightPosition: 'top',
      highlightSize: 0.2,
      highlightIntensity: 0.9,
      wallShade: 0.6,
    },
  },
  {
    id: 'builtin_segmented_bellows',
    name: '波纹管',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'segmented_pipe',
    styleParams: {
      opacity: 1,
      hardness: 0.7,
      segmentLength: 6,
      segmentGap: 1,
      segmentTaper: 0.15,
      bellowsWidth: 0.4,
      highlightPosition: 'top',
      highlightSize: 0.25,
      wallShade: 0.4,
    },
  },
  {
    id: 'builtin_segmented_bamboo',
    name: '竹节',
    type: 'pixel',
    size: 4,
    shape: [[true]],
    style: 'segmented_pipe',
    styleParams: {
      opacity: 1,
      hardness: 0.8,
      segmentLength: 10,
      segmentGap: 2,
      segmentTaper: 0.1,
      bellowsWidth: 0.2,
      highlightPosition: 'left',
      highlightSize: 0.3,
      wallShade: 0.35,
    },
  },
  {
    id: 'builtin_segmented_chain',
    name: '链条管道',
    type: 'pixel',
    size: 3,
    shape: [[true]],
    style: 'segmented_pipe',
    styleParams: {
      opacity: 1,
      hardness: 0.9,
      segmentLength: 4,
      segmentGap: 3,
      segmentTaper: 0.3,
      bellowsWidth: 0.5,
      highlightPosition: 'top',
      highlightSize: 0.2,
      wallShade: 0.55,
    },
  },
  {
    id: 'builtin_vine_blood',
    name: '血管',
    type: 'pixel',
    size: 5,
    shape: [[true]],
    style: 'vine',
    styleParams: {
      opacity: 1,
      hardness: 0.7,
      lightDirection: 315,
      lightIntensity: 0.6,
      veinColor: '#4a1a2e',
      organicNoise: 0.25,
      branchDensity: 0.2,
      seed: 42,
    },
  },
  {
    id: 'builtin_vine_plant',
    name: '藤蔓',
    type: 'pixel',
    size: 4,
    shape: [[true]],
    style: 'vine',
    styleParams: {
      opacity: 1,
      hardness: 0.6,
      lightDirection: 270,
      lightIntensity: 0.5,
      veinColor: '#2d4a1a',
      organicNoise: 0.4,
      branchDensity: 0.35,
      seed: 7,
    },
  },
  {
    id: 'builtin_vine_tentacle',
    name: '触手',
    type: 'pixel',
    size: 6,
    shape: [[true]],
    style: 'vine',
    styleParams: {
      opacity: 1,
      hardness: 0.5,
      lightDirection: 0,
      lightIntensity: 0.7,
      veinColor: '#1a2a3a',
      organicNoise: 0.5,
      branchDensity: 0.1,
      seed: 13,
    },
  },

  // ---- V8: Shape Stamp Brushes ----

  {
    id: 'builtin_star_solid',
    name: '实心五角星',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'star',
    styleParams: {
      opacity: 1,
      hardness: 1,
      innerColor: '#ffee55',
      outerColor: '#ff8800',
      spikeCount: 5,
      hollow: false,
      innerOuterRatio: 0.4,
      rotation: 0,
    },
  },
  {
    id: 'builtin_star_hollow',
    name: '空心五角星',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'star',
    styleParams: {
      opacity: 1,
      hardness: 1,
      innerColor: '#ffee55',
      outerColor: '#ff8800',
      spikeCount: 5,
      hollow: true,
      innerOuterRatio: 0.4,
      rotation: 0,
    },
  },
  {
    id: 'builtin_star_dual_color',
    name: '双色五角星',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'star',
    styleParams: {
      opacity: 1,
      hardness: 1,
      innerColor: '#ffffff',
      outerColor: '#3366ff',
      spikeCount: 5,
      hollow: false,
      innerOuterRatio: 0.45,
      rotation: 0,
    },
  },
  {
    id: 'builtin_star_six',
    name: '六芒星',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'star',
    styleParams: {
      opacity: 1,
      hardness: 1,
      innerColor: '#cc88ff',
      outerColor: '#6600cc',
      spikeCount: 6,
      hollow: false,
      innerOuterRatio: 0.5,
      rotation: 0,
    },
  },
  {
    id: 'builtin_heart_red',
    name: '红色爱心',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'heart',
    styleParams: {
      opacity: 1,
      hardness: 1,
      innerColor: '#ff6688',
      outerColor: '#cc0033',
      lobeWidth: 1.0,
      pointiness: 0.6,
    },
  },
  {
    id: 'builtin_heart_pink',
    name: '粉色爱心',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'heart',
    styleParams: {
      opacity: 0.9,
      hardness: 0.9,
      innerColor: '#ffaacc',
      outerColor: '#ff6699',
      lobeWidth: 1.1,
      pointiness: 0.4,
    },
  },
  {
    id: 'builtin_sphere_default',
    name: '高光球',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'sphere',
    styleParams: {
      opacity: 1,
      hardness: 1,
      highlightX: -0.25,
      highlightY: -0.3,
      highlightRadius: 0.3,
      highlightBrightness: 0.8,
      shadingIntensity: 0.7,
    },
  },
  {
    id: 'builtin_sphere_metal',
    name: '金属球',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'sphere',
    styleParams: {
      opacity: 1,
      hardness: 1,
      highlightX: -0.3,
      highlightY: -0.35,
      highlightRadius: 0.2,
      highlightBrightness: 1.0,
      shadingIntensity: 0.9,
    },
  },
  {
    id: 'builtin_droplet_water',
    name: '水滴',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'droplet',
    styleParams: {
      opacity: 0.85,
      hardness: 0.8,
      tailLength: 0.5,
      tailDirection: 270,
    },
  },
  {
    id: 'builtin_droplet_rain',
    name: '雨滴',
    type: 'pixel',
    size: 8,
    shape: [[true]],
    style: 'droplet',
    styleParams: {
      opacity: 0.7,
      hardness: 0.9,
      tailLength: 0.7,
      tailDirection: 240,
    },
  },
  {
    id: 'builtin_bubble_soap',
    name: '肥皂泡',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'bubble',
    styleParams: {
      opacity: 0.6,
      hardness: 0.9,
      iridescence: 0.5,
      membraneThickness: 0.08,
      reflectionSize: 0.25,
    },
  },
  {
    id: 'builtin_bubble_rainbow',
    name: '彩虹泡泡',
    type: 'pixel',
    size: 16,
    shape: [[true]],
    style: 'bubble',
    styleParams: {
      opacity: 0.5,
      hardness: 0.8,
      iridescence: 0.9,
      membraneThickness: 0.06,
      reflectionSize: 0.2,
    },
  },
  {
    id: 'builtin_punct_exclamation',
    name: '感叹号!',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'punctuation',
    styleParams: {
      opacity: 1,
      punctuationType: 'exclamation',
      outlineThickness: 1,
      outlineColor: '#000000',
    },
  },
  {
    id: 'builtin_punct_question',
    name: '问号?',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'punctuation',
    styleParams: {
      opacity: 1,
      punctuationType: 'question',
      outlineThickness: 1,
      outlineColor: '#000000',
    },
  },
  {
    id: 'builtin_punct_ellipsis',
    name: '省略号...',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'punctuation',
    styleParams: {
      opacity: 1,
      punctuationType: 'ellipsis',
      outlineThickness: 0,
      outlineColor: '#000000',
    },
  },
  {
    id: 'builtin_punct_interrobang',
    name: '疑问惊叹?!',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'punctuation',
    styleParams: {
      opacity: 1,
      punctuationType: 'interrobang',
      outlineThickness: 1,
      outlineColor: '#000000',
    },
  },
  {
    id: 'builtin_emoji_happy',
    name: '开心脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'happy',
      eyeSize: 0.25,
      mouthCurve: 1,
    },
  },
  {
    id: 'builtin_emoji_sad',
    name: '伤心脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'sad',
      eyeSize: 0.25,
      mouthCurve: -0.8,
    },
  },
  {
    id: 'builtin_emoji_angry',
    name: '生气脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'angry',
      eyeSize: 0.2,
      mouthCurve: -0.5,
    },
  },
  {
    id: 'builtin_emoji_cool',
    name: '墨镜脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'cool',
      eyeSize: 0.3,
      mouthCurve: 0.6,
    },
  },
  {
    id: 'builtin_emoji_love',
    name: '花痴脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'love',
      eyeSize: 0.3,
      mouthCurve: 1,
    },
  },
  {
    id: 'builtin_emoji_surprised',
    name: '惊讶脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'surprised',
      eyeSize: 0.3,
      mouthCurve: 0,
    },
  },
  {
    id: 'builtin_emoji_wink',
    name: '眨眼脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'wink',
      eyeSize: 0.25,
      mouthCurve: 0.8,
    },
  },
  {
    id: 'builtin_emoji_dizzy',
    name: '晕眩脸',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'emoji',
    styleParams: {
      opacity: 1,
      hardness: 1,
      emojiType: 'dizzy',
      eyeSize: 0.25,
      mouthCurve: 0,
    },
  },

  // ---- V9: Industrial / Mechanical Brushes ----
  {
    id: 'builtin_bevel_metal',
    name: '金属倒角缝',
    type: 'pixel',
    size: 8,
    shape: [[true]],
    style: 'bevel_seam',
    styleParams: {
      opacity: 1,
      hardness: 1,
      bevelDepth: 0.5,
      bevelWidth: 0.3,
      bevelLightDir: 315,
      bevelShadow: 0.8,
      grooveColor: '#222222',
    },
  },
  {
    id: 'builtin_bevel_shallow',
    name: '浅槽接缝',
    type: 'pixel',
    size: 6,
    shape: [[true]],
    style: 'bevel_seam',
    styleParams: {
      opacity: 1,
      hardness: 1,
      bevelDepth: 0.25,
      bevelWidth: 0.2,
      bevelLightDir: 270,
      bevelShadow: 0.4,
      grooveColor: '#444444',
    },
  },
  {
    id: 'builtin_bevel_deep',
    name: '深沟焊接缝',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'bevel_seam',
    styleParams: {
      opacity: 1,
      hardness: 1,
      bevelDepth: 0.8,
      bevelWidth: 0.35,
      bevelLightDir: 315,
      bevelShadow: 0.9,
      grooveColor: '#111111',
    },
  },
  {
    id: 'builtin_prism_bar',
    name: '棱柱条',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'prism',
    styleParams: {
      opacity: 1,
      hardness: 1,
      topWidthRatio: 0.7,
      prismHeight: 0.8,
      prismLightDir: 315,
      topFaceBrightness: 0.6,
      edgeHighlight: 0.5,
    },
  },
  {
    id: 'builtin_prism_pedestal',
    name: '棱台座',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'prism',
    styleParams: {
      opacity: 1,
      hardness: 1,
      topWidthRatio: 0.5,
      prismHeight: 0.9,
      prismLightDir: 300,
      topFaceBrightness: 0.7,
      edgeHighlight: 0.6,
    },
  },
  {
    id: 'builtin_prism_sharp',
    name: '尖棱柱',
    type: 'pixel',
    size: 8,
    shape: [[true]],
    style: 'prism',
    styleParams: {
      opacity: 1,
      hardness: 1,
      topWidthRatio: 0.3,
      prismHeight: 0.7,
      prismLightDir: 330,
      topFaceBrightness: 0.5,
      edgeHighlight: 0.8,
    },
  },
  {
    id: 'builtin_plate_metal',
    name: '金属板材',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'plate',
    styleParams: {
      opacity: 1,
      hardness: 1,
      plateThickness: 0.5,
      plateBevel: 0.2,
      plateLightDir: 315,
      surfaceTexture: 0.1,
      plateEdgeBright: 0.4,
    },
  },
  {
    id: 'builtin_plate_thick',
    name: '厚面板',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'plate',
    styleParams: {
      opacity: 1,
      hardness: 1,
      plateThickness: 0.7,
      plateBevel: 0.3,
      plateLightDir: 300,
      surfaceTexture: 0.05,
      plateEdgeBright: 0.5,
    },
  },
  {
    id: 'builtin_plate_rust',
    name: '锈蚀板材',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'plate',
    styleParams: {
      opacity: 1,
      hardness: 0.8,
      plateThickness: 0.6,
      plateBevel: 0.15,
      plateLightDir: 315,
      surfaceTexture: 0.5,
      plateEdgeBright: 0.2,
    },
  },
  {
    id: 'builtin_grille_standard',
    name: '标准格栅',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'grille',
    styleParams: {
      opacity: 1,
      hardness: 1,
      slatCount: 4,
      slatGap: 0.3,
      slatDepth: 0.7,
      frameWidth: 0.15,
      openingColor: '#111111',
    },
  },
  {
    id: 'builtin_grille_fine',
    name: '密格栅',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'grille',
    styleParams: {
      opacity: 1,
      hardness: 1,
      slatCount: 8,
      slatGap: 0.2,
      slatDepth: 0.5,
      frameWidth: 0.1,
      openingColor: '#0a0a0a',
    },
  },
  {
    id: 'builtin_grille_louver',
    name: '百叶窗',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'grille',
    styleParams: {
      opacity: 1,
      hardness: 1,
      slatCount: 5,
      slatGap: 0.4,
      slatDepth: 0.8,
      frameWidth: 0.12,
      openingColor: '#000000',
    },
  },
  {
    id: 'builtin_vent_round',
    name: '圆形散热口',
    type: 'pixel',
    size: 12,
    shape: [[true]],
    style: 'vent',
    styleParams: {
      opacity: 1,
      hardness: 1,
      ventOpening: 0.6,
      rimThickness: 0.12,
      rimColor: '#aaaaaa',
      innerDepth: 0.8,
      hasSlats: true,
      ventSlatCount: 3,
    },
  },
  {
    id: 'builtin_vent_exhaust',
    name: '排气喷口',
    type: 'pixel',
    size: 14,
    shape: [[true]],
    style: 'vent',
    styleParams: {
      opacity: 1,
      hardness: 1,
      ventOpening: 0.5,
      rimThickness: 0.15,
      rimColor: '#cccccc',
      innerDepth: 0.9,
      hasSlats: false,
      ventSlatCount: 0,
    },
  },
  {
    id: 'builtin_vent_slat',
    name: '条缝散热口',
    type: 'pixel',
    size: 10,
    shape: [[true]],
    style: 'vent',
    styleParams: {
      opacity: 1,
      hardness: 1,
      ventOpening: 0.7,
      rimThickness: 0.08,
      rimColor: '#bbbbbb',
      innerDepth: 0.6,
      hasSlats: true,
      ventSlatCount: 5,
    },
  },
];
